// /api/listings.js — Siterifty server-side listings handler (v2 — rebuilt)
// ─────────────────────────────────────────────────────────────────────────────
// Full rewrite of the previous listings.js. Same responsibilities, new action
// names and response envelope:
//
//   POST /api/listings  { action, idToken, ...params }
//
//   action: 'listing.create'  { idToken, type, title, description, url?,
//                                isTemplate?, financials?, tech?, images?,
//                                appIcon?, category?, gameFile?, settings?,
//                                transferMethods?, gameType?, videoUrl?,
//                                previewUrl?, platforms?, apkUrl?,
//                                apkStorageUrl?, apkIpaFileName? }
//                              → { ok: true, data: { listingId, plan } }
//                              → { ok: false, error: { message, code } }
//
//   action: 'listing.update'  { idToken, listingId, ...same fields as above }
//                              → { ok: true, data: {} }
//                              Owner only. `type`/`ownerId`/`ownerEmail`/
//                              `createdAt`/`status` are never accepted from
//                              the client — fixed at creation time.
//
//   action: 'listing.delete'  { idToken, listingId }
//                              → { ok: true, data: {} }
//                              Owner only.
//
//   action: 'listing.report'  { idToken, listingId, reason, details? }
//                              → { ok: true, data: { reportId } }
//                              Rate-limited per reporter (REPORT_LIMITS).
//
//   action: 'listing.file-url' { idToken?, listingId, storagePath }
//                              → { ok: true, data: { url } }
//                              Public — no auth required. Mints a signed URL
//                              for a binary build file (apk/aab/obb/apks/
//                              xapk/ipa) attached to an ACTIVE listing, so
//                              marketplace visitors can preview/download it.
//                              Unlike deal.js's escrow-get-download-url, this
//                              is repeatable (not one-time) and never deletes
//                              the underlying file — it's a public listing
//                              asset, not an escrow deliverable. storagePath
//                              must actually be attached to the listing
//                              (main apk/ipa field, additionalFiles array, or
//                              a notLiveBuildFiles entry) or the request is
//                              rejected, so this can't be used to mint a
//                              signed URL for an arbitrary/unrelated path.
//
//   action: 'listing.feed'    { idToken, seed?, cursor?, pageSize? }
//                              → { ok: true, data: { listings, seed, cursor, exhausted } }
//                              Server-owned browse feed — replaces the old
//                              client-side Firestore query+shuffle. Active
//                              listings are pulled per type (website/app/
//                              game) via Admin SDK, ordered by a deterministic
//                              hash of (seed + listingId) so the order is
//                              reproducible across pages without server-side
//                              session storage, then interleaved 1-1-1 so no
//                              long run of a single type ever appears. `seed`
//                              is generated by the server on first call (no
//                              seed in the request) and must be echoed back
//                              by the client on every subsequent page so the
//                              shuffle stays stable and non-repeating within
//
//   action: 'listing.mine'    { idToken, status? }
//                              → { ok: true, data: { listings } }
//                              Caller's own listings (any status, or one
//                              status if provided), newest first. Powers the
//                              Seller Dashboard — NOT the same as listing.feed,
//                              which is public/active-only with no owner filter.
//                              that browsing session; a new seed = a fresh
//                              random order (e.g. on manual refresh). `cursor`
//                              is an opaque per-type offset object the client
//                              must echo back verbatim, not construct itself.
//
//   action: 'listing.daily-stats' { idToken, listingId, days }
//                              → { ok: true, data: { days: [{ date, impressionCount, viewCount }, ...] } }
//                              Owner only. Per-day impression/view history for
//                              one listing, oldest first, zero-filled for any
//                              date with no traffic. Backed by
//                              listings/{listingId}/dailyStats/{YYYY-MM-DD},
//                              written alongside the lifetime counters in
//                              _bumpListingCounter. Powers the Seller
//                              Dashboard's Views & Clicks trend chart.
//
// Response envelope (every response, success or failure, uses this shape):
//   Success: { ok: true,  data: {...} }
//   Failure: { ok: false, error: { message: string, code: string } }
//
// Resilience note: the weekly-listing-cap check queries `listings` with a
// composite filter (ownerId == , createdAt >=) that requires a Firestore
// composite index. If that index is missing or still building, Firestore
// throws FAILED_PRECONDITION. Previously this bubbled up as a raw 500 and
// blocked listing creation entirely. Now that specific failure is caught and
// turned into a clear, safe denial (never silently allows the listing through
// uncapped) — see _checkWeeklyCap below.
//
// Firestore paths touched:
//   listings/{listingId}
//   listings/{listingId}/dailyStats/{YYYY-MM-DD}
//   reports/*
//   users/{uid}/reportsMade/*   (kept for parity — currently unused directly;
//                                 rate-limit bookkeeping lives on users/{uid}
//                                 .reportTimestamps, same as before)
//
// All mutations run via Firebase Admin SDK. The client must NOT write
// directly to any of the above paths.
// ─────────────────────────────────────────────────────────────────────────────

import { initializeApp, getApps, cert } from 'firebase-admin/app';
import { getFirestore, FieldValue, FieldPath, Timestamp } from 'firebase-admin/firestore';
import { LIMITS } from './limits.js';
import { supabaseCreateSignedUrl, findAccountById } from './storage.js';

// ── Internal call into /api/aistudio for AI checks ──
// Fire-and-forget — a report must never fail or slow down because the AI is
// slow/down. Only ever called for content a human has already flagged (a
// reported listing), never on every new listing submission, to stay within
// Gemini vision's small daily quota (~20 req/day per model).
async function triggerAiCheck(action, payload) {
  try {
    const base = process.env.PUBLIC_BASE_URL
      || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : null);
    if (!base) {
      console.warn('[listings] no base URL configured (PUBLIC_BASE_URL/VERCEL_URL) — skipping AI check trigger');
      return;
    }
    await fetch(`${base}/api/aistudio`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Internal-Token': process.env.AISTUDIO_INTERNAL_TOKEN || '',
      },
      body: JSON.stringify({ action, ...payload }),
    });
  } catch (err) {
    console.error('[listings] AI check trigger failed (non-fatal):', err.message);
  }
}

// ── Firebase Admin singleton ─────────────────────────────────────────────────
function getAdminDb() {
  if (!getApps().length) {
    initializeApp({
      credential: cert({
        projectId:   process.env.FIREBASE_PROJECT_ID,
        clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
        privateKey:  process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
      }),
    });
  }
  return getFirestore();
}

// ── Firebase ID token verification via REST ──────────────────────────────────
const FIREBASE_WEB_API_KEY = 'AIzaSyCMdI_bIYse6j3GyGDBnbE6FoGNnPKaMao';

async function verifyFirebaseToken(idToken) {
  const res = await fetch(
    `https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${FIREBASE_WEB_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ idToken }),
    }
  );
  if (!res.ok) throw new ApiError('Invalid Firebase token', 'AUTH_INVALID', 401);
  const data = await res.json();
  const user = data.users?.[0];
  if (!user) throw new ApiError('User not found', 'AUTH_USER_NOT_FOUND', 401);
  return user; // { localId, email, ... }
}

// ── Typed API error — carries a machine-readable code alongside the message ─
class ApiError extends Error {
  constructor(message, code = 'INTERNAL', statusCode = 500) {
    super(message);
    this.code = code;
    this.statusCode = statusCode;
  }
}

function ok(res, data = {}, statusCode = 200) {
  return res.status(statusCode).json({ ok: true, data });
}
function fail(res, err) {
  const statusCode = err.statusCode || 500;
  const code = err.code || 'INTERNAL';
  const message = err.message || 'Internal error';
  return res.status(statusCode).json({ ok: false, error: { message, code } });
}

// ── Allowed listing types ────────────────────────────────────────────────────
const LISTING_TYPES = ['website', 'app', 'game'];

// ── Report abuse limits ──────────────────────────────────────────────────────
const REPORT_LIMITS = {
  maxPerDay: 5,
  periodMs:  24 * 60 * 60 * 1000,
  reasons: [
    'scam', 'fake-metrics', 'stolen-content', 'prohibited-item',
    'misleading', 'duplicate', 'other',
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Main handler
// ─────────────────────────────────────────────────────────────────────────────
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ ok: false, error: { message: 'Method not allowed', code: 'METHOD_NOT_ALLOWED' } });
  }

  const { action, idToken } = req.body || {};
  // listing.feed and listing.file-url are public — signed-out visitors can
  // browse listings and preview/download an already-attached build file
  // without being logged in. Every other action (create/update/delete/
  // report) still requires auth.
  const PUBLIC_ACTIONS = ['listing.feed', 'listing.file-url', 'listing.impression', 'listing.view'];
  if (!idToken && !PUBLIC_ACTIONS.includes(action)) {
    return fail(res, new ApiError('Missing auth token', 'AUTH_MISSING', 401));
  }

  try {
    switch (action) {
      case 'listing.create': return ok(res, await handleCreate(req.body, idToken));
      case 'listing.update': return ok(res, await handleUpdate(req.body, idToken));
      case 'listing.delete': return ok(res, await handleDelete(req.body, idToken));
      case 'listing.report': return ok(res, await handleReport(req.body, idToken));
      case 'listing.feed':   return ok(res, await handleFeed(req.body, idToken));
      case 'listing.mine':   return ok(res, await handleMine(req.body, idToken));
      case 'listing.daily-stats': return ok(res, await handleDailyStats(req.body, idToken));
      case 'listing.file-url': return ok(res, await handleFileUrl(req.body, idToken));
      case 'listing.impression': return ok(res, await handleImpression(req.body, idToken));
      case 'listing.view':   return ok(res, await handleView(req.body, idToken));
      default:
        return fail(res, new ApiError('Unknown action', 'UNKNOWN_ACTION', 400));
    }
  } catch (err) {
    console.error('[listings.js]', action, err.message);
    return fail(res, err);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared validation helpers
// ─────────────────────────────────────────────────────────────────────────────
function validateTitleDesc(title, description) {
  const L = LIMITS.listing;
  const cleanTitle = (title || '').trim();
  const cleanDesc  = (description || '').trim();

  if (cleanTitle.length < L.titleMinLength || cleanTitle.length > L.titleMaxLength) {
    throw new ApiError(
      `Title must be between ${L.titleMinLength} and ${L.titleMaxLength} characters.`,
      'TITLE_LENGTH', 400
    );
  }
  if (cleanDesc.length < L.descMinLength || cleanDesc.length > L.descMaxLength) {
    throw new ApiError(
      `Description must be between ${L.descMinLength} and ${L.descMaxLength} characters.`,
      'DESC_LENGTH', 400
    );
  }
  return { cleanTitle, cleanDesc };
}

function validateUrlIfWebsite(type, isTemplate, url) {
  if (type === 'website' && !isTemplate) {
    if (!url || !/^https?:\/\/.+/.test(url)) {
      throw new ApiError('Please provide a valid URL starting with https://.', 'INVALID_URL', 400);
    }
  }
}

// Builds the nested sub-objects (financials/tech/settings/platforms) shared
// between create and update, from whatever subset of fields was sent.
function buildFinancials(financials) {
  if (!financials || typeof financials !== 'object') return null;
  const rev = Number.isFinite(financials.revenue)  ? financials.revenue  : null;
  const exp = Number.isFinite(financials.expenses) ? financials.expenses : null;
  const out = {
    price:    Number.isFinite(financials.price) ? financials.price : null,
    revenue:  rev,
    expenses: exp,
    profit:   (rev !== null && exp !== null) ? rev - exp : null,
  };
  if (financials.monetizationModel) out.monetizationModel = String(financials.monetizationModel).slice(0, 60);
  if (Number.isFinite(financials.subscriptionPriceMonthly)) out.subscriptionPriceMonthly = financials.subscriptionPriceMonthly;
  if (Number.isFinite(financials.subscriptionPriceAnnual))  out.subscriptionPriceAnnual  = financials.subscriptionPriceAnnual;
  return out;
}

function buildTech(tech) {
  if (!tech || typeof tech !== 'object') return null;
  return {
    frontend:     tech.frontend     ? String(tech.frontend).slice(0, 60)     : null,
    backend:      tech.backend      ? String(tech.backend).slice(0, 60)      : null,
    database:     tech.database     ? String(tech.database).slice(0, 60)     : null,
    monetization: tech.monetization ? String(tech.monetization).slice(0, 60) : null,
  };
}

function buildSettings(settings, fallbackCategory) {
  if (!settings || typeof settings !== 'object') return null;
  return {
    category:  settings.category  ? String(settings.category).slice(0, 60)  : (fallbackCategory || ''),
    age:       settings.age       ? String(settings.age).slice(0, 40)       : '',
    location:  settings.location  ? String(settings.location).slice(0, 120) : '',
    structure: settings.structure ? String(settings.structure).slice(0, 40) : '',
    reason:    settings.reason    ? String(settings.reason).slice(0, 500)   : '',
  };
}

function buildPlatforms(platforms) {
  if (!platforms || typeof platforms !== 'object') return null;
  return {
    selected:   Array.isArray(platforms.selected) ? platforms.selected.map(String) : [],
    iosUrl:     platforms.iosUrl     ? String(platforms.iosUrl).slice(0, 500)     : null,
    androidUrl: platforms.androidUrl ? String(platforms.androidUrl).slice(0, 500) : null,
    webUrl:     platforms.webUrl     ? String(platforms.webUrl).slice(0, 500)     : null,
    previewUrl: platforms.previewUrl ? String(platforms.previewUrl).slice(0, 500) : null,
  };
}

// Each additional file the client uploaded via /api/storage comes back as
// either { url, filename, contentType, size } (text/web assets — html/css/
// js/etc, which storage.js gives a real fetchable url) or
// { storagePath, filename, contentType, size } (binary build files — apk/
// aab/obb/apks/xapk/ipa, which storage.js only gives a storagePath that
// must be resolved via listing.file-url at render time). Both shapes are
// kept as-is; the frontend/render side is what decides which to use
// directly vs. sign on demand.
function buildAdditionalFiles(additionalFiles) {
  if (!Array.isArray(additionalFiles)) return null;
  return additionalFiles.slice(0, 10).map(f => {
    const out = {
      filename:    f.filename    ? String(f.filename).slice(0, 300)    : '',
      contentType: f.contentType ? String(f.contentType).slice(0, 120) : '',
      size:        Number.isFinite(f.size) ? f.size : null,
    };
    if (f.url)         out.url         = String(f.url).slice(0, 1000);
    if (f.storagePath) out.storagePath = String(f.storagePath).slice(0, 500);
    return out;
  });
}

// notLive: which platforms are marked "not live yet" ({ ios, android, web }
// booleans, or a single global flag under notLive.global for the App form's
// all-platforms "Not Live" tile). notLiveBuildFiles: the actual uploaded
// build file(s) per platform (or under "global"), same dual url/storagePath
// shape as buildAdditionalFiles above, since the per-platform text uploads
// (web) get a real url and binary uploads (ios/android/global) only get a
// storagePath.
function buildNotLive(notLive) {
  if (!notLive || typeof notLive !== 'object') return null;
  const out = {};
  for (const key of ['ios', 'android', 'web', 'global']) {
    out[key] = Boolean(notLive[key]);
  }
  return out;
}

function buildNotLiveBuildFiles(notLiveBuildFiles) {
  if (!notLiveBuildFiles || typeof notLiveBuildFiles !== 'object') return null;
  const out = {};
  for (const [platform, files] of Object.entries(notLiveBuildFiles)) {
    if (!Array.isArray(files)) continue;
    out[platform] = files.slice(0, 10).map(f => {
      const item = {
        filename:    f.filename    ? String(f.filename).slice(0, 300)    : '',
        contentType: f.contentType ? String(f.contentType).slice(0, 120) : '',
        size:        Number.isFinite(f.size) ? f.size : null,
      };
      if (f.url)         item.url         = String(f.url).slice(0, 1000);
      if (f.storagePath) item.storagePath = String(f.storagePath).slice(0, 500);
      return item;
    });
  }
  return out;
}

// ── Weekly listing cap check ─────────────────────────────────────────────────
// Wrapped so a missing/still-building Firestore composite index (ownerId ==,
// createdAt >=) turns into a clear, safe denial instead of a raw 500 that
// looks like the whole publish flow is broken. "Safe" means: on index
// failure we DENY the listing rather than silently letting it through
// uncapped — the cap is a real business rule, not just cosmetics.
async function _checkWeeklyCap(tx, db, uid, plan) {
  const max = LIMITS.weeklyListingLimit[plan] ?? LIMITS.weeklyListingLimit.free;
  if (max === null) return; // unlimited plan — nothing to check

  const now = new Date();
  const weekStart = new Date(now);
  weekStart.setUTCHours(0, 0, 0, 0);
  weekStart.setUTCDate(now.getUTCDate() - now.getUTCDay());
  const weekStartTs = Timestamp.fromDate(weekStart);

  let countSnap;
  try {
    countSnap = await tx.get(
      db.collection('listings')
        .where('ownerId', '==', uid)
        .where('createdAt', '>=', weekStartTs)
    );
  } catch (err) {
    if (err.code === 9 || /FAILED_PRECONDITION/.test(err.message || '')) {
      console.error('[listings.js] _checkWeeklyCap missing index — create it:', err.message);
      throw new ApiError(
        "We're temporarily unable to verify your weekly listing limit. Please try again in a few minutes.",
        'CAP_CHECK_UNAVAILABLE', 503
      );
    }
    throw err;
  }

  if (countSnap.size >= max) {
    throw new ApiError(
      `Weekly listing limit reached (${countSnap.size}/${max} on the ${plan} plan). Upgrade your plan or wait until next week.`,
      'WEEKLY_CAP_REACHED', 409
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// listing.create
// ─────────────────────────────────────────────────────────────────────────────
async function handleCreate(body, idToken) {
  const {
    type, title, description, url, isTemplate,
    financials, tech, images, appIcon, category, gameFile,
    settings, transferMethods, gameType, videoUrl, previewUrl,
    platforms, apkUrl, apkStorageUrl, apkIpaFileName,
    additionalFiles, notLive, notLiveBuildFiles,
  } = body;

  if (!LISTING_TYPES.includes(type)) {
    throw new ApiError('Invalid listing type', 'INVALID_TYPE', 400);
  }

  const { cleanTitle, cleanDesc } = validateTitleDesc(title, description);
  validateUrlIfWebsite(type, isTemplate, url);

  const fbUser = await verifyFirebaseToken(idToken);
  const uid = fbUser.localId;

  const db      = getAdminDb();
  const userRef = db.collection('users').doc(uid);
  const listingRef = db.collection('listings').doc();

  const result = await db.runTransaction(async tx => {
    const userSnap = await tx.get(userRef);
    if (!userSnap.exists) throw new ApiError('User document not found', 'USER_NOT_FOUND', 404);

    const plan = userSnap.data().plan || 'free';
    await _checkWeeklyCap(tx, db, uid, plan);

    const listingDoc = {
      ownerId:     uid,
      ownerEmail:  fbUser.email || '',
      type,
      title:       cleanTitle,
      description: cleanDesc,
      status:      'active',
      isTemplate:  Boolean(isTemplate),
      createdAt:   FieldValue.serverTimestamp(),
    };

    if (url) listingDoc.url = String(url).slice(0, 500);

    const fin = buildFinancials(financials);
    if (fin) listingDoc.financials = fin;

    const techObj = buildTech(tech);
    if (techObj) listingDoc.tech = techObj;

    if (Array.isArray(images)) {
      listingDoc.images     = images.slice(0, 6).map(String);
      listingDoc.imageCover = listingDoc.images[0] || null;
    }
    if (appIcon)        listingDoc.appIcon        = String(appIcon);
    if (category)       listingDoc.category       = String(category).slice(0, 60);
    if (gameFile)       listingDoc.gameFile        = String(gameFile);
    if (gameType)       listingDoc.gameType         = String(gameType).slice(0, 20);
    if (videoUrl)       listingDoc.videoUrl         = String(videoUrl).slice(0, 500);
    if (previewUrl)     listingDoc.previewUrl       = String(previewUrl).slice(0, 500);
    if (apkUrl)         listingDoc.apkUrl           = String(apkUrl);
    if (apkStorageUrl)  listingDoc.apkStorageUrl    = String(apkStorageUrl);
    if (apkIpaFileName) listingDoc.apkIpaFileName   = String(apkIpaFileName);

    const additionalFilesArr = buildAdditionalFiles(additionalFiles);
    if (additionalFilesArr) listingDoc.additionalFiles = additionalFilesArr;

    const notLiveObj = buildNotLive(notLive);
    if (notLiveObj) listingDoc.notLive = notLiveObj;

    const notLiveBuildFilesObj = buildNotLiveBuildFiles(notLiveBuildFiles);
    if (notLiveBuildFilesObj) listingDoc.notLiveBuildFiles = notLiveBuildFilesObj;

    const settingsObj = buildSettings(settings, category);
    if (settingsObj) listingDoc.settings = settingsObj;

    if (Array.isArray(transferMethods)) listingDoc.transferMethods = transferMethods.map(String);

    const platformsObj = buildPlatforms(platforms);
    if (platformsObj) listingDoc.platforms = platformsObj;

    tx.set(listingRef, listingDoc);
    return { plan };
  });

  return { listingId: listingRef.id, plan: result.plan };
}

// ─────────────────────────────────────────────────────────────────────────────
// listing.update — owner only. Never trusts/accepts ownerId, ownerEmail,
// type, status, or createdAt from the request body.
// ─────────────────────────────────────────────────────────────────────────────
async function handleUpdate(body, idToken) {
  const {
    listingId, title, description, url,
    financials, tech, settings, images, appIcon, category,
    gameFile, videoUrl, previewUrl, platforms, transferMethods,
    apkUrl, apkStorageUrl, apkIpaFileName,
    additionalFiles, notLive, notLiveBuildFiles,
  } = body;

  if (!listingId) throw new ApiError('Missing listingId', 'MISSING_LISTING_ID', 400);

  const fbUser = await verifyFirebaseToken(idToken);
  const uid = fbUser.localId;

  const db  = getAdminDb();
  const ref = db.collection('listings').doc(listingId);
  const snap = await ref.get();

  if (!snap.exists) throw new ApiError('Listing not found', 'LISTING_NOT_FOUND', 404);
  const existing = snap.data();
  if (existing.ownerId !== uid) {
    throw new ApiError('You can only edit your own listings', 'FORBIDDEN', 403);
  }

  const { cleanTitle, cleanDesc } = validateTitleDesc(title, description);
  validateUrlIfWebsite(existing.type, existing.isTemplate, url);

  const update = {
    title:       cleanTitle,
    description: cleanDesc,
    updatedAt:   FieldValue.serverTimestamp(),
  };

  if (url !== undefined)        update.url        = String(url).slice(0, 500);
  if (category)                  update.category   = String(category).slice(0, 60);
  if (videoUrl !== undefined)    update.videoUrl   = videoUrl ? String(videoUrl).slice(0, 500) : null;
  if (previewUrl !== undefined)  update.previewUrl = previewUrl ? String(previewUrl).slice(0, 500) : null;
  if (gameFile)                  update.gameFile   = String(gameFile);
  if (appIcon !== undefined)     update.appIcon    = appIcon ? String(appIcon) : null;
  if (apkUrl !== undefined)          update.apkUrl          = apkUrl ? String(apkUrl) : null;
  if (apkStorageUrl !== undefined)   update.apkStorageUrl   = apkStorageUrl ? String(apkStorageUrl) : null;
  if (apkIpaFileName !== undefined)  update.apkIpaFileName  = apkIpaFileName ? String(apkIpaFileName) : null;

  if (additionalFiles !== undefined) {
    update.additionalFiles = buildAdditionalFiles(additionalFiles) || [];
  }
  if (notLive !== undefined) {
    update.notLive = buildNotLive(notLive) || { ios: false, android: false, web: false, global: false };
  }
  if (notLiveBuildFiles !== undefined) {
    update.notLiveBuildFiles = buildNotLiveBuildFiles(notLiveBuildFiles) || {};
  }

  const fin = buildFinancials(financials);
  if (fin) {
    update.financials = {
      ...existing.financials,
      price:    Number.isFinite(financials.price)    ? financials.price    : existing.financials?.price    ?? null,
      revenue:  Number.isFinite(financials.revenue)  ? financials.revenue  : existing.financials?.revenue  ?? null,
      expenses: Number.isFinite(financials.expenses) ? financials.expenses : existing.financials?.expenses ?? null,
    };
    update.financials.profit = (update.financials.revenue ?? 0) - (update.financials.expenses ?? 0);
  }

  const techObj = buildTech(tech);
  if (techObj) update.tech = techObj;

  if (settings && typeof settings === 'object') {
    update.settings = { ...existing.settings, ...settings };
  }
  if (Array.isArray(images)) {
    update.images     = images.slice(0, 6).map(String);
    update.imageCover = update.images[0] || null;
  }
  if (platforms && typeof platforms === 'object') {
    update.platforms = { ...existing.platforms, ...platforms };
  }
  if (Array.isArray(transferMethods)) {
    update.transferMethods = transferMethods.map(String);
  }

  await ref.update(update);
  return {};
}

// ─────────────────────────────────────────────────────────────────────────────
// listing.delete — owner only.
// ─────────────────────────────────────────────────────────────────────────────
async function handleDelete(body, idToken) {
  const { listingId } = body;
  if (!listingId) throw new ApiError('Missing listingId', 'MISSING_LISTING_ID', 400);

  const fbUser = await verifyFirebaseToken(idToken);
  const uid = fbUser.localId;

  const db  = getAdminDb();
  const ref = db.collection('listings').doc(listingId);
  const snap = await ref.get();

  if (!snap.exists) throw new ApiError('Listing not found', 'LISTING_NOT_FOUND', 404);
  if (snap.data().ownerId !== uid) {
    throw new ApiError('You can only delete your own listings', 'FORBIDDEN', 403);
  }

  await ref.delete();
  return {};
}

// ─────────────────────────────────────────────────────────────────────────────
// listing.report — rate-limited per reporter.
// ─────────────────────────────────────────────────────────────────────────────
async function handleReport(body, idToken) {
  const { listingId, reason, details } = body;
  if (!listingId) throw new ApiError('Missing listingId', 'MISSING_LISTING_ID', 400);
  if (!REPORT_LIMITS.reasons.includes(reason)) {
    throw new ApiError('Invalid report reason', 'INVALID_REASON', 400);
  }

  const fbUser = await verifyFirebaseToken(idToken);
  const uid = fbUser.localId;

  const db = getAdminDb();
  const listingSnap = await db.collection('listings').doc(listingId).get();
  if (!listingSnap.exists) throw new ApiError('Listing not found', 'LISTING_NOT_FOUND', 404);

  const listing = listingSnap.data();
  if (listing.ownerId === uid) {
    throw new ApiError('You cannot report your own listing', 'SELF_REPORT', 400);
  }

  const userRef = db.collection('users').doc(uid);
  const now = Date.now();

  const result = await db.runTransaction(async tx => {
    const userSnap = await tx.get(userRef);
    if (!userSnap.exists) throw new ApiError('User document not found', 'USER_NOT_FOUND', 404);

    const priorReports = Array.isArray(userSnap.data().reportTimestamps)
      ? userSnap.data().reportTimestamps
      : [];
    const recent = priorReports.filter(t => (now - t) < REPORT_LIMITS.periodMs);

    if (recent.length >= REPORT_LIMITS.maxPerDay) {
      throw new ApiError(
        `You've reached the limit of ${REPORT_LIMITS.maxPerDay} reports per day. Please try again later.`,
        'REPORT_RATE_LIMITED', 429
      );
    }

    const updatedTimestamps = [...recent, now];
    tx.update(userRef, { reportTimestamps: updatedTimestamps });

    const reportRef = db.collection('reports').doc();
    tx.set(reportRef, {
      listingId,
      listingTitle:    listing.title || '',
      listingOwnerId:  listing.ownerId,
      reportedBy:      uid,
      reportedByEmail: fbUser.email || '',
      reason,
      details:  (details || '').slice(0, 1000),
      status:   'open',
      createdAt: FieldValue.serverTimestamp(),
    });

    return { reportId: reportRef.id, coverImage: listing.imageCover || (Array.isArray(listing.images) ? listing.images[0] : null) };
  });

  // AI image check — ONE image only (the listing's cover photo), and only
  // because this listing was just reported by a human. This deliberately
  // does not loop over all up-to-6 images on the listing (would blow through
  // Gemini vision's ~20/day quota fast) and never runs on ordinary listing
  // submission — only here, on a reported item. Fire-and-forget so the
  // report submission itself never waits on or fails because of the AI
  // call. The verdict (appropriate/concerns/summary) gets written directly
  // onto the report doc by aistudio.js once the check completes.
  if (result.coverImage) {
    triggerAiCheck('analyze-reported-image', {
      imageUrl: result.coverImage,
      reportId: result.reportId,
      context: `Reported listing "${listing.title || ''}" — report reason: ${reason}.`,
    }).catch(() => {});
  }

  return { reportId: result.reportId };
}

// ─────────────────────────────────────────────────────────────────────────────
// listing.file-url — public signed-URL mint for a listing's build file(s).
// Binary build files (apk/aab/obb/apks/xapk/ipa) never get a permanent
// public url from /api/storage (see storage.js TRANSFER_FILE_EXTS) — only a
// storagePath. This resolves that storagePath into a short-lived signed URL,
// but ONLY if it's actually attached to this listing and the listing is
// currently active, so the endpoint can't be used to fetch an arbitrary
// storagePath belonging to someone else's file.
// ─────────────────────────────────────────────────────────────────────────────
const LISTING_FILE_URL_TTL_SECONDS = 300; // 5 minutes — re-mint on each view/click, same pattern as deal.js

function _storagePathsOnListing(listing) {
  const paths = new Set();
  if (listing.apkStorageUrl) paths.add(listing.apkStorageUrl);
  if (Array.isArray(listing.additionalFiles)) {
    for (const f of listing.additionalFiles) {
      if (f && f.storagePath) paths.add(f.storagePath);
    }
  }
  if (listing.notLiveBuildFiles && typeof listing.notLiveBuildFiles === 'object') {
    for (const files of Object.values(listing.notLiveBuildFiles)) {
      if (!Array.isArray(files)) continue;
      for (const f of files) {
        if (f && f.storagePath) paths.add(f.storagePath);
      }
    }
  }
  return paths;
}

async function handleFileUrl(body, idToken) {
  const { listingId, storagePath } = body;
  if (!listingId)    throw new ApiError('Missing listingId', 'MISSING_LISTING_ID', 400);
  if (!storagePath)  throw new ApiError('Missing storagePath', 'MISSING_STORAGE_PATH', 400);

  // Signed-in or signed-out visitors can both request this — verify the
  // token only if one was sent (mirrors handleFeed's pattern), so a bad
  // token from a logged-out browser's stale state doesn't hard-fail a
  // public listing view.
  if (idToken) await verifyFirebaseToken(idToken);

  const db = getAdminDb();
  const snap = await db.collection('listings').doc(listingId).get();
  if (!snap.exists) throw new ApiError('Listing not found', 'LISTING_NOT_FOUND', 404);

  const listing = snap.data();
  if (listing.status !== 'active') {
    throw new ApiError('This listing is not currently available', 'LISTING_NOT_ACTIVE', 403);
  }

  if (!_storagePathsOnListing(listing).has(storagePath)) {
    throw new ApiError('File does not belong to this listing', 'FILE_NOT_ON_LISTING', 403);
  }

  // storagePath format: "<accountId>@@<uploaderUid>--filename...", same
  // convention as storage.js/deal.js.
  const pathMatch = storagePath.match(/^(\d+)@@(.+)$/);
  if (!pathMatch) throw new ApiError('Malformed storagePath', 'BAD_STORAGE_PATH', 400);
  const [, accountId, uidScopedName] = pathMatch;

  try {
    const account = findAccountById(accountId);
    const url = await supabaseCreateSignedUrl(account, uidScopedName, LISTING_FILE_URL_TTL_SECONDS);
    return { url, expiresIn: LISTING_FILE_URL_TTL_SECONDS };
  } catch (err) {
    console.error('[listings.js] listing.file-url sign error:', err.message);
    throw new ApiError('Could not generate download link', 'SIGN_FAILED', 500);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// listing.feed — server-owned browse feed
// ─────────────────────────────────────────────────────────────────────────────
// Deterministic string hash (FNV-1a-ish) used to turn (seed + listingId) into
// a stable pseudo-random sort key. Same seed + same listingId always produces
// the same key, so ordering is reproducible across paginated calls without
// needing to persist per-session state server-side — the client just echoes
// the seed back on every subsequent page request.
function _seededSortKey(seed, id) {
  let h = 2166136261 ^ seed;
  const s = String(id);
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  // Unsigned 32-bit float in [0, 1) — stable for a given (seed, id) pair.
  return (h >>> 0) / 4294967296;
}

const FEED_TYPES = ['website', 'app', 'game'];
const FEED_DEFAULT_PAGE_SIZE = 21; // 7 of each type per page, 1-1-1 interleaved
const FEED_MAX_PAGE_SIZE = 60;
const FEED_MAX_POOL_PER_TYPE = 500; // hard cap per type fetched from Firestore per request

// Mirrors marketplace.js's client-side SR_PAID_PLANS exactly — a seller on
// any of these plans counts as "premium" for feed prioritization. Ordered
// lowest → highest so index = rank; used to prefer higher plans over lower
// ones when multiple premium listings are competing for the same slot.
const SR_PAID_PLANS = ['starter', 'growth', 'pro'];

// Mirrors marketplace.js's _isBoosted exactly (server-side Timestamp fields
// come back with .toMillis(), plain numbers stay numbers).
function _isBoosted(listing) {
  const until = listing.boostedUntil;
  if (!until) return false;
  const ms = typeof until === 'number' ? until
    : (until.toMillis ? until.toMillis() : (until.seconds ? until.seconds * 1000 : 0));
  return ms > Date.now();
}

// Top-of-batch priority promotion, applied to EVERY lazy-load batch (not
// just the first), with a different slot count per batch position:
//
//   Batch 1 (first load, all per-type cursors at 0): top 3 slots.
//     Target mix: 2 boosted + 1 premium-plan.
//   Batch 2+ (every subsequent scroll-triggered load): top 2 slots.
//     Target mix: 1 boosted + 1 premium-plan.
//
// Each target slot is filled from its designated pool (boosted or premium)
// when available. If a pool runs short, the shortfall falls back to the
// OTHER pool (e.g. no premium listings left → that slot tries boosted
// instead, and vice versa) so we still fill as many priority slots as we
// can from *either* pool combined. Only once both pools are exhausted does
// a slot give up and stay as whatever the normal shuffle put there — never
// forced, never padded with non-priority listings.
//
// Among premium candidates, higher-tier plans are preferred first (pro >
// growth > starter) — see _rankPremium.
const BATCH1_SLOTS = { total: 3, boosted: 2, premium: 1 };
const BATCHN_SLOTS = { total: 2, boosted: 1, premium: 1 };

// Higher plan = higher rank. Non-premium / unknown = -1 (never wins a
// premium slot over an actual paid plan).
function _planRank(plan) {
  return SR_PAID_PLANS.indexOf(plan);
}

// Applies the priority promotion in place on an already-interleaved `page`
// array. `boostedIds` / `premiumIds` are Sets of listing IDs eligible for
// each pool (a listing can be in both — boosted AND premium-owned — in
// which case it can satisfy either slot type). `ownerPlanById` maps
// ownerId -> plan string, used to rank premium candidates by tier.
// `slotsCfg` is one of BATCH1_SLOTS / BATCHN_SLOTS above.
function _applyPriorityPromotion(page, boostedIds, premiumIds, ownerPlanById, slotsCfg) {
  const n = Math.min(slotsCfg.total, page.length);
  if (n === 0) return page;

  // Build ordered candidate queues (indices into `page`, sitting outside the
  // top n) for each pool. Premium candidates are sorted highest-plan-first
  // so a Pro listing gets pulled forward before a Starter one.
  const boostedElsewhere = [];
  const premiumElsewhere = [];
  for (let i = n; i < page.length; i++) {
    const l = page[i];
    if (boostedIds.has(l.id)) boostedElsewhere.push(i);
    if (premiumIds.has(l.id)) premiumElsewhere.push(i);
  }
  premiumElsewhere.sort((a, b) => {
    const rankA = _planRank(ownerPlanById.get(page[a].ownerId));
    const rankB = _planRank(ownerPlanById.get(page[b].ownerId));
    return rankB - rankA; // higher plan first
  });

  // Build the ordered list of "what each of the n slots wants first" —
  // e.g. for batch 1: [boosted, boosted, premium]. Slot order matters only
  // for which target gets first pick when both pools are healthy; the
  // fallback logic below handles shortfalls regardless of order.
  const wants = [];
  for (let i = 0; i < slotsCfg.boosted; i++) wants.push('boosted');
  for (let i = 0; i < slotsCfg.premium; i++) wants.push('premium');
  while (wants.length < n) wants.push('boosted'); // defensive pad, shouldn't trigger given current configs

  const takeFrom = (queue) => (queue.length ? queue.shift() : null);

  for (let slot = 0; slot < n; slot++) {
    const already = boostedIds.has(page[slot].id) || premiumIds.has(page[slot].id);
    if (already) continue; // this slot already holds a priority listing, leave it

    const primary = wants[slot];
    const secondary = primary === 'boosted' ? 'premium' : 'boosted';
    const primaryQueue = primary === 'boosted' ? boostedElsewhere : premiumElsewhere;
    const secondaryQueue = secondary === 'boosted' ? boostedElsewhere : premiumElsewhere;

    let sourceIdx = takeFrom(primaryQueue);
    if (sourceIdx === null) sourceIdx = takeFrom(secondaryQueue); // fallback to the other pool
    if (sourceIdx === null) continue; // both pools exhausted — leave this slot as the random draw

    const tmp = page[slot];
    page[slot] = page[sourceIdx];
    page[sourceIdx] = tmp;
  }

  // Tail pass: the remaining slots (everything after the promoted top-n)
  // should default to free/non-boosted listings — boosted listings that
  // didn't win a promoted slot shouldn't just spill into the "regular"
  // section either, since that would dilute the boost's whole point. We
  // only fall back to showing a leftover boosted listing in the tail if
  // there genuinely aren't enough free ones to fill it — never dropping
  // listings, just reordering so free is preferred when there's a choice.
  const freeElsewhere = [];
  const boostedTailCandidates = [];
  for (let i = n; i < page.length; i++) {
    if (boostedIds.has(page[i].id)) boostedTailCandidates.push(i);
    else freeElsewhere.push(i);
  }

  if (boostedTailCandidates.length && freeElsewhere.length) {
    // Walk the tail slots in order; anywhere currently holding a
    // non-promoted boosted listing, try to swap in a free one from further
    // down. Two pointers: `writeSlot` scans forward for boosted-occupied
    // tail slots, `freeIdx` scans forward through free candidates.
    let freePtr = 0;
    for (const boostedIdx of boostedTailCandidates) {
      if (freePtr >= freeElsewhere.length) break; // out of free listings to swap in
      const freeIdx = freeElsewhere[freePtr];
      if (freeIdx <= boostedIdx) { freePtr++; continue; } // only pull from further back, not swap backwards
      const tmp = page[boostedIdx];
      page[boostedIdx] = page[freeIdx];
      page[freeIdx] = tmp;
      freePtr++;
    }
  }

  return page;
}

async function handleFeed(body, idToken) {
  // Public browsing — signed-out visitors can view the feed. If a token IS
  // provided we still verify it (rather than silently ignoring a bad one),
  // since a verified uid may be used for personalization later; but no
  // token is a perfectly valid guest request, not an error.
  if (idToken) await verifyFirebaseToken(idToken);
  const db = getAdminDb();

  let { seed, cursor, pageSize, type } = body || {};

  // Optional single-type filter (mirrors the frontend's type chips). When
  // set, we only fetch/shuffle that one bucket — no interleaving needed.
  const activeTypes = (type && FEED_TYPES.includes(type)) ? [type] : FEED_TYPES;

  // A missing/invalid seed means "start a new shuffled session" — e.g. first
  // load, or the user pulled to refresh. A fresh seed each time is exactly
  // what gives each user (and each refresh) their own random order.
  if (!Number.isInteger(seed)) seed = Math.floor(Math.random() * 2 ** 31);

  const size = Math.min(FEED_MAX_PAGE_SIZE, Math.max(1, Number(pageSize) || FEED_DEFAULT_PAGE_SIZE));
  const perTypeWanted = Math.ceil(size / activeTypes.length);

  // Opaque per-type offsets. Client must echo this back verbatim — it is not
  // a real Firestore cursor (we can't paginate a virtual shuffled order with
  // startAfter), just "how many of this type have already been sent".
  const safeCursor = (cursor && typeof cursor === 'object') ? cursor : {};
  const offsets = {};
  for (const t of activeTypes) offsets[t] = Number.isInteger(safeCursor[t]) ? Math.max(0, safeCursor[t]) : 0;

  // Whether this call is the very first batch of a fresh, unfiltered browse
  // session (all per-type cursors at 0) — computed from the INCOMING cursor,
  // before this page's offsets are advanced below. Determines both whether
  // promotion runs at all (single-type filtered views are skipped, same as
  // before) and which slot config (BATCH1_SLOTS vs BATCHN_SLOTS) applies.
  const isUnfiltered = activeTypes.length === FEED_TYPES.length;
  const isFirstBatch = isUnfiltered && activeTypes.every(t => (Number.isInteger(safeCursor[t]) ? safeCursor[t] : 0) === 0);

  // Pull each type's full active pool (capped), sort deterministically by the
  // seeded key, then slice out just the window this page needs. Re-fetching
  // the whole pool per call is simple and correct (new listings just enter
  // the shuffle naturally); if pools get huge later this can be optimized
  // with a stored randomField, but this is fine at current scale.
  const buckets = {};
  const exhaustedByType = {};
  await Promise.all(activeTypes.map(async (t) => {
    const snap = await db.collection('listings')
      .where('status', '==', 'active')
      .where('type', '==', t)
      .limit(FEED_MAX_POOL_PER_TYPE)
      .get();

    const items = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    items.sort((a, b) => _seededSortKey(seed, a.id) - _seededSortKey(seed, b.id));

    const start = offsets[t];
    const slice = items.slice(start, start + perTypeWanted);
    buckets[t] = slice;
    offsets[t] = start + slice.length;
    exhaustedByType[t] = (start + slice.length) >= items.length;
  }));

  // Interleave 1-1-1 (website, app, game, website, app, game, ...) so no long
  // run of a single type ever appears on screen, even though each bucket's
  // internal order is independently shuffled. When filtered to a single
  // type, this just yields that bucket's shuffled order directly.
  const page = [];
  const maxLen = Math.max(...activeTypes.map(t => buckets[t].length));
  for (let i = 0; i < maxLen && page.length < size; i++) {
    for (const t of activeTypes) {
      if (buckets[t][i]) page.push(buckets[t][i]);
      if (page.length >= size) break;
    }
  }

  // Priority promotion runs on every batch of an unfiltered browse (not just
  // the first) — single-type filtered views are left untouched, same as
  // before, since "top of feed" isn't really meaningful there.
  if (isUnfiltered && page.length) {
    // Boost status is on the listing doc directly. Plan lives on
    // users/{ownerId}, so we need one batched lookup across the distinct
    // owners in this page — a single db.getAll() call, not one read per
    // listing, and it's the SAME lookup the client would otherwise have to
    // do per-card via mpGetSeller, so doing it here also saves the client
    // an extra round trip per card (see ownerPlan attached below).
    const ownerIds = [...new Set(page.map(l => l.ownerId).filter(Boolean))];
    const ownerPlanById = new Map();
    if (ownerIds.length) {
      // getAll accepts up to 300 refs — page sizes here are capped at
      // FEED_MAX_PAGE_SIZE (60) so a single owner per listing worst-case
      // still fits comfortably under that limit.
      const userRefs = ownerIds.map(id => db.collection('users').doc(id));
      const userSnaps = await db.getAll(...userRefs);
      userSnaps.forEach(snap => {
        if (snap.exists) ownerPlanById.set(snap.id, snap.data()?.plan || 'free');
      });
    }

    // Attach ownerPlan directly onto each listing so the client can render
    // the plan-tier badge (Starter/Growth/Pro) straight from feed data,
    // with zero extra per-card Firestore reads and nothing to re-fetch on
    // subsequent renders of the same listing.
    page.forEach(l => { l.ownerPlan = l.ownerId ? (ownerPlanById.get(l.ownerId) || 'free') : 'free'; });

    const boostedIds = new Set(page.filter(l => _isBoosted(l)).map(l => l.id));
    const premiumIds = new Set(page.filter(l => SR_PAID_PLANS.includes(l.ownerPlan)).map(l => l.id));

    const slotsCfg = isFirstBatch ? BATCH1_SLOTS : BATCHN_SLOTS;
    _applyPriorityPromotion(page, boostedIds, premiumIds, ownerPlanById, slotsCfg);
  }

  const exhausted = activeTypes.every(t => exhaustedByType[t]);

  return {
    listings: page,
    seed,
    cursor: offsets,
    exhausted,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// listing.mine  { idToken, status? }  → { listings }
//
// Caller's OWN listings, any status (active/sold/removed/etc — whatever the
// app uses), newest first. Powers the Seller Dashboard, which needs a
// seller's real listing set (title, counters) rather than the public browse
// feed (handleFeed above), which is deliberately status:'active'-only and
// has no per-owner filter. `status` narrows to one status if provided;
// omitted/blank returns everything the caller owns.
// ─────────────────────────────────────────────────────────────────────────────
async function handleMine(body, idToken) {
  const fbUser = await verifyFirebaseToken(idToken);
  const uid = fbUser.localId;
  const { status } = body || {};

  const db = getAdminDb();
  let query = db.collection('listings').where('ownerId', '==', uid);
  if (status && typeof status === 'string') {
    query = query.where('status', '==', status);
  }
  query = query.orderBy('createdAt', 'desc');

  // Same composite-index risk as _checkWeeklyCap above: (ownerId ==,
  // createdAt desc) — and the status-filtered variant (ownerId ==, status ==,
  // createdAt desc) — each need their own Firestore composite index. Wrapped
  // so a missing/still-building index surfaces as a clear, safe error instead
  // of a raw 500 that looks like the Seller Dashboard itself is broken.
  let snap;
  try {
    snap = await query.get();
  } catch (err) {
    if (err.code === 9 || /FAILED_PRECONDITION/.test(err.message || '')) {
      console.error('[listings.js] listing.mine missing index — create it:', err.message);
      throw new ApiError(
        "We're temporarily unable to load your listings. Please try again in a few minutes.",
        'MINE_INDEX_UNAVAILABLE', 503
      );
    }
    throw err;
  }
  const listings = snap.docs.map(d => ({ id: d.id, ...d.data() }));

  return { listings };
}


// ─────────────────────────────────────────────────────────────────────────────
// listing.daily-stats  { idToken, listingId, days }  → { days: [...] }
//
// Per-day impression/view history for one listing, read from
// listings/{listingId}/dailyStats/{YYYY-MM-DD} (written by _bumpListingCounter
// above). Owner-only — without this check any signed-in user could pull
// another seller's per-day traffic just by knowing a listingId, which is
// worse than the lifetime counters (already public on the listing doc) since
// day-by-day shape can leak things like launch timing or promo activity.
//
// Returns exactly `days` entries, oldest first, zero-filled for any date with
// no traffic yet (no dailyStats doc) so the client never has to reason about
// gaps — array length is always `days` and index 0 is always `days`-1 ago.
// ─────────────────────────────────────────────────────────────────────────────
async function handleDailyStats(body, idToken) {
  const fbUser = await verifyFirebaseToken(idToken);
  const uid = fbUser.localId;
  const { listingId, days } = body || {};

  if (!listingId || typeof listingId !== 'string') {
    throw new ApiError('Missing listingId', 'MISSING_LISTING_ID', 400);
  }
  const numDays = Number(days);
  if (!Number.isInteger(numDays) || numDays < 1 || numDays > 366) {
    throw new ApiError('Invalid days', 'INVALID_DAYS', 400);
  }

  const db = getAdminDb();
  const listingRef = db.collection('listings').doc(listingId);
  const listingSnap = await listingRef.get();
  if (!listingSnap.exists) throw new ApiError('Listing not found', 'LISTING_NOT_FOUND', 404);
  if (listingSnap.data().ownerId !== uid) {
    throw new ApiError('Not authorized to view this listing\'s stats', 'NOT_OWNER', 403);
  }

  // Build the date-key range first so we can do a single ranged query on
  // document ID (dailyStats doc IDs are "YYYY-MM-DD", which sort
  // lexicographically the same as chronologically) instead of `days`
  // individual .get() calls.
  const todayUTC = new Date();
  todayUTC.setUTCHours(0, 0, 0, 0);
  const dateKeys = [];
  for (let i = numDays - 1; i >= 0; i--) {
    const d = new Date(todayUTC);
    d.setUTCDate(d.getUTCDate() - i);
    dateKeys.push(d.toISOString().slice(0, 10));
  }

  const dailyCol = listingRef.collection('dailyStats');
  const rangeSnap = await dailyCol
    .where(FieldPath.documentId(), '>=', dateKeys[0])
    .where(FieldPath.documentId(), '<=', dateKeys[dateKeys.length - 1])
    .get();

  const byDate = {};
  rangeSnap.docs.forEach(d => { byDate[d.id] = d.data(); });

  const daysOut = dateKeys.map(date => ({
    date,
    impressionCount: byDate[date]?.impressionCount || 0,
    viewCount: byDate[date]?.viewCount || 0,
  }));

  return { days: daysOut };
}


// All three are public (signed-out visitors browse, open, and click listings
// too) and all use FieldValue.increment(), which is an atomic server-side op
// — safe under concurrent hits, no read-modify-write race, no lost updates.
//
// "impression" (`impressionCount`) = the listing CARD was rendered in a list
//   (scrolled into view / loaded on screen). Weakest signal — visitor may not
//   have actually read it.
// "view" (`viewCount`) = the visitor actually OPENED the listing detail modal
//   — they've seen the full listing, not just the card.
// "click" — no longer a generic click-through counter. It is tracked as two
//   outcomes tied specifically to the Send Deal CTA in deal.js:
//     `successfulClickCount` = Send Deal clicked AND the deal was created.
//     `failedClickCount`     = Send Deal clicked but it did not go through.
//   (See deal.js handleCreateDeal wrapper for those two.)
//
// These are intentionally separate counters (impression does not imply view,
// view does not imply click) so the seller can see a real funnel — card
// impressions → detail opens → successful vs failed deal attempts — instead
// of one lump "traffic" number.
//
// Abuse note: this endpoint is unauthenticated by design (anonymous traffic
// is real traffic sellers want counted), which means it can't be fully
// bot/refresh-proofed at the API layer alone — that's normal for view
// counters (same tradeoff every analytics pixel makes). What we DO guard
// against here is the cheap stuff: missing/garbage listingId, listings that
// don't exist, and a single client hammering the same listing in a tight
// loop (best-effort per-instance in-memory debounce below). Real bot
// filtering, if ever needed, belongs behind something like a Vercel Edge/
// WAF rate limit in front of this route, not in application code.
const VIEW_CLICK_DEBOUNCE_MS = 4000; // per (listingId, kind) — collapses rapid double-fires (e.g. React double-render, double-tap)
const _recentHits = new Map(); // key: `${kind}:${listingId}:${voterKey}` -> timestamp
// Best-effort cleanup so this map never grows unbounded on a long-lived
// serverless instance. Not persisted — fine, since its only job is smoothing
// out rapid duplicate fires within a single warm instance, not exact dedup.
function _pruneRecentHits() {
  const cutoff = Date.now() - VIEW_CLICK_DEBOUNCE_MS * 5;
  for (const [key, ts] of _recentHits) {
    if (ts < cutoff) _recentHits.delete(key);
  }
}

async function _bumpListingCounter(body, idToken, field, kind) {
  const { listingId } = body || {};
  if (!listingId || typeof listingId !== 'string') {
    throw new ApiError('Missing listingId', 'MISSING_LISTING_ID', 400);
  }

  // Same pattern as handleFileUrl/handleFeed: verify the token only if one
  // was actually sent, so a stale/bad token from a logged-out browser never
  // hard-fails what is otherwise a perfectly valid anonymous hit. We don't
  // currently use the uid for anything here, but knowing signed-in vs
  // anonymous is available for future per-user dedup if needed.
  let uid = null;
  if (idToken) {
    try {
      const user = await verifyFirebaseToken(idToken);
      uid = user.localId;
    } catch (_) {
      // Bad token on an anonymous-friendly action — don't block the hit,
      // just treat it as anonymous.
    }
  }

  // Cheap same-instance debounce, keyed by uid when known, else by nothing
  // (best-effort only — different serverless instances/cold starts won't
  // share this map, which is fine; it's a smoothing layer, not a security
  // boundary).
  const voterKey = uid || 'anon';
  const dedupeKey = `${kind}:${listingId}:${voterKey}`;
  const now = Date.now();
  const lastHit = _recentHits.get(dedupeKey);
  if (lastHit && (now - lastHit) < VIEW_CLICK_DEBOUNCE_MS) {
    return { counted: false };
  }
  _recentHits.set(dedupeKey, now);
  if (_recentHits.size > 5000) _pruneRecentHits();

  const db = getAdminDb();
  const ref = db.collection('listings').doc(listingId);

  const snap = await ref.get();
  if (!snap.exists) throw new ApiError('Listing not found', 'LISTING_NOT_FOUND', 404);

  // Today's UTC date bucket, e.g. "2026-07-10". Matches the doc-ID format
  // handleDailyStats reads back (see below) — UTC keeps the bucket boundary
  // consistent regardless of which region the serverless instance runs in,
  // rather than drifting with each request's local time.
  const dateKey = new Date().toISOString().slice(0, 10);
  const dailyRef = ref.collection('dailyStats').doc(dateKey);

  // Same atomic increment as the lifetime counter, fired alongside it (not
  // chained) so one slow write can't delay the other and a failure in one
  // doesn't block the other from landing.
  await Promise.all([
    ref.update({ [field]: FieldValue.increment(1) }),
    dailyRef.set({ [field]: FieldValue.increment(1) }, { merge: true }),
  ]);

  return { counted: true };
}

async function handleImpression(body, idToken) {
  return _bumpListingCounter(body, idToken, 'impressionCount', 'impression');
}

async function handleView(body, idToken) {
  return _bumpListingCounter(body, idToken, 'viewCount', 'view');
}

export const config = {
  api: { bodyParser: { sizeLimit: '2mb' } },
};
